"""initial

Revision ID: 3840cee322e3
Revises: 
Create Date: 2026-05-31 19:18:49.232587+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3840cee322e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_chat_messages',
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_chat_messages_client_id'), 'community_chat_messages', ['client_id'], unique=False)
    op.create_index(op.f('ix_community_chat_messages_id'), 'community_chat_messages', ['id'], unique=False)
    op.create_table('community_track_votes',
    sa.Column('track_key', sa.String(length=200), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('reaction', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_track_votes_client_id'), 'community_track_votes', ['client_id'], unique=False)
    op.create_index(op.f('ix_community_track_votes_id'), 'community_track_votes', ['id'], unique=False)
    op.create_index(op.f('ix_community_track_votes_track_key'), 'community_track_votes', ['track_key'], unique=False)
    op.create_table('stations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('azuracast_id', sa.Integer(), nullable=True),
    sa.Column('azuracast_shortcode', sa.String(length=100), nullable=True),
    sa.Column('stream_url', sa.String(length=500), nullable=False),
    sa.Column('hls_url', sa.String(length=500), nullable=True),
    sa.Column('nowplaying_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('total_listeners', sa.Integer(), nullable=False),
    sa.Column('unique_listeners', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_index(op.f('ix_stations_name'), 'stations', ['name'], unique=False)
    op.create_index(op.f('ix_stations_slug'), 'stations', ['slug'], unique=True)
    op.create_table('listeners',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listeners_id'), 'listeners', ['id'], unique=False)
    op.create_index(op.f('ix_listeners_session_id'), 'listeners', ['session_id'], unique=True)
    op.create_table('tracks',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artist', sa.String(length=500), nullable=False),
    sa.Column('album', sa.String(length=500), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('isrc', sa.String(length=50), nullable=True),
    sa.Column('musicbrainz_id', sa.String(length=100), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('azuracast_media_id', sa.String(length=100), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isrc')
    )
    op.create_index(op.f('ix_tracks_artist'), 'tracks', ['artist'], unique=False)
    op.create_index(op.f('ix_tracks_id'), 'tracks', ['id'], unique=False)
    op.create_index(op.f('ix_tracks_title'), 'tracks', ['title'], unique=False)
    op.create_table('ratings',
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('user_identifier', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'user_identifier', name='uq_track_user_rating')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_index(op.f('ix_ratings_user_identifier'), 'ratings', ['user_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_user_identifier'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_tracks_title'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_artist'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_listeners_session_id'), table_name='listeners')
    op.drop_index(op.f('ix_listeners_id'), table_name='listeners')
    op.drop_table('listeners')
    op.drop_index(op.f('ix_stations_slug'), table_name='stations')
    op.drop_index(op.f('ix_stations_name'), table_name='stations')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_community_track_votes_track_key'), table_name='community_track_votes')
    op.drop_index(op.f('ix_community_track_votes_id'), table_name='community_track_votes')
    op.drop_index(op.f('ix_community_track_votes_client_id'), table_name='community_track_votes')
    op.drop_table('community_track_votes')
    op.drop_index(op.f('ix_community_chat_messages_id'), table_name='community_chat_messages')
    op.drop_index(op.f('ix_community_chat_messages_client_id'), table_name='community_chat_messages')
    op.drop_table('community_chat_messages')
    # ### end Alembic commands ###
