"""add_community_member

Revision ID: 26d26421ad11
Revises: 3840cee322e3
Create Date: 2026-05-31 19:53:59.782775+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d26421ad11'
down_revision = '3840cee322e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_members',
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_supporter', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_members_client_id'), 'community_members', ['client_id'], unique=True)
    op.create_index(op.f('ix_community_members_id'), 'community_members', ['id'], unique=False)
    op.create_index(op.f('ix_community_members_nickname'), 'community_members', ['nickname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_members_nickname'), table_name='community_members')
    op.drop_index(op.f('ix_community_members_id'), table_name='community_members')
    op.drop_index(op.f('ix_community_members_client_id'), table_name='community_members')
    op.drop_table('community_members')
    # ### end Alembic commands ###
