"""add_access_token

Revision ID: a7fd0b58ad9b
Revises: 26d26421ad11
Create Date: 2026-05-31 20:09:32.039675+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fd0b58ad9b'
down_revision = '26d26421ad11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_members', sa.Column('access_token', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_community_members_access_token'), 'community_members', ['access_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_members_access_token'), table_name='community_members')
    op.drop_column('community_members', 'access_token')
    # ### end Alembic commands ###
