ansible_host: 10.1.0.92
ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/pve_ed25519
is_anker: true

guests:
  - { id: 100, type: pct }
  - { id: 101, type: pct }
  - { id: 110, type: pct }
  - { id: 130, type: pct }
  - { id: 150, type: pct }
  - { id: 210, type: qm }
  - { id: 240, type: qm }
  - { id: 300, type: qm }
