---
compose_stack_name: paperless
compose_service_name: homeserver-compose-paperless.service
compose_template: stacks/paperless/docker-compose.yml.j2
compose_env_template: stacks/paperless/stack.env.j2
compose_http_bind: 10.1.0.23
compose_http_port: 8000
paperless_time_zone: Europe/Berlin
paperless_ocr_language: deu
paperless_admin_user: frawoadmin
paperless_frontend_user: frontend
paperless_consume_host_dir: /var/lib/docker/volumes/paperless_consume/_data
paperless_archive_host_dir: /var/lib/docker/volumes/paperless_media/_data/documents/archive
paperless_nextcloud_base_url: http://10.1.0.21
paperless_nextcloud_rclone_remote: nextcloud_frontend
paperless_nextcloud_remote_root: Paperless
paperless_nextcloud_inbox_dir: Eingang
paperless_nextcloud_archive_dir: Archiv
paperless_nextcloud_bridge_service_name: homeserver2027-paperless-nextcloud-bridge.service
paperless_nextcloud_bridge_timer_name: homeserver2027-paperless-nextcloud-bridge.timer
paperless_nextcloud_bridge_on_boot_sec: 3m
paperless_nextcloud_bridge_on_unit_active_sec: 5m
