[proxmox]
# Tailscale-optimiertes Inventory
anker-pve ansible_host=100.69.179.87 ansible_user=root    # Intern: 192.168.2.10
pve ansible_host=100.91.20.116 ansible_user=root          # Intern: 192.168.178.172 (Requires TS-SSH Auth)
toolbox ansible_host=100.99.206.128 ansible_user=root

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

